server:
  port: 8083
spring:
  application:
    name: spring-cloud-gateway
  zipkin:
    base-url: http://localhost:8091
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: fegin-auth
          #调用的服务
          uri: lb://spring-cloud-feign
          #拦截路径
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      #          routes：具体的路由信息，是一个数组，每一个路由基本包含部分：
      #            id：这个路由的唯一id，不定义的话为一个uuid
      #            uri：http请求为lb://前缀 + 服务id；ws请求为lb:ws://前缀 + 服务id；表示将请求负载到哪一个服务上
      #            predicates：表示这个路由的请求匹配规则，只有符合这个规则的请求才会走这个路由。为一个数组，每个规则为并且的关系。
      #            filters：请求转发前的filter，为一个数组。
      #            order：这个路由的执行order
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS