server:
  port: 8086
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juejitianyafei/spring-cloud-demo
          search-paths: spring-cloud-config-respo
          username:
          password:
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'  #SpringBootActuator监控暴露所有接口